# fly.toml app configuration file generated for neural-notes-embed-api on 2025-07-20T02:19:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neural-notes-embed-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8001
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # [[http_service.checks]]
  #   interval = "20s"
  #   timeout = "10s"
  #   grace_period = "30s"  # ğŸ’¡ í•µì‹¬: ì„œë²„ ëœ¨ê¸° ì „ì—” ì²´í¬í•˜ì§€ ë§ˆ!
  #   method = "get"
  #   path = "/health"  # FastAPIì— ì´ ê²½ë¡œ ì¶”ê°€ í•„ìš”

[[vm]]
  size = "shared-cpu-1x"
  memory = 1024
